"""initial migration

Revision ID: 85124fca2cd6
Revises: 
Create Date: 2025-01-02 04:32:06.535183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85124fca2cd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'description')
    # ### end Alembic commands ###
